rgbd_input:
  ros__parameters:
    rgb_image_topic: /camera/color/image_raw
    rgb_camera_info_topic: /camera/color/camera_info
    depth_image_topic: /camera/aligned_depth_to_color/image_raw
    depth_camera_info_topic: /camera/aligned_depth_to_color/camera_info
    point_cloud_topic: ""
    imu_raw_topic: /camera/imu
    imu_topic: /imu/filtered
    use_point_cloud: false
    use_rgbd_sync: false
    approximate_sync: true
    approx_sync_max_interval: 0.02
    replay_approx_sync_max_interval: 0.1
    depth_registered_to_color: true
    require_registered_depth: true
    require_imu: true
    require_tf_static: true
    required_tf_frames: []
    qos_profile: sensor_data
